apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /ifs/data/Laas/nfsmount1
    server: 10.63.17.15

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/volumes/1
    server: 10.63.17.15


apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/volumes/2
    server: 10.63.17.15
